# Generated by Django 2.2.5 on 2019-09-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_author',
            field=models.CharField(max_length=60),
        ),
    ]
