# Generated by Django 2.2.5 on 2019-09-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_joboffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobOffer',
        ),
    ]
